GET http://localhost:2424



### Test dashboard 
GET http://localhost:2424/dashboard

### data endpoint
GET http://localhost:2424/api/data/

### for adding user 
POST http://localhost:2424/api/data/
Content-Type:application/json

 {
    "name":"Dharan"
 }

### delete
DELETE http://localhost:2424/api/data